name: Basic Matrix Example

on: workflow_call

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18, 20]
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      run: echo "setup node with ${{ matrix.node-version }}"
