name: Multi-Dimensional Matrix

on: workflow_call

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [16, 18, 20]
        include:
          # Add specific combinations
          - os: ubuntu-latest
            node-version: 14
            experimental: true
        exclude:
          # Remove specific combinations
          - os: macos-latest
            node-version: 16
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      run: echo "node setup ${{ matrix.node-version }}"
    - name: Extra step for experimental builds
      if: matrix.experimental
      run: echo "npm run test:experimental"
